### ISSUE TITLE
Connection lost immediately after login

### ISSUE THREAD

**Issue by Paladin1979** [kreezxil/World-of-Dragons#332] opened 2019-09-16 07:28 UTC
**Describe the bug**
Every time I log in, I get an "Internal Exception: io.netty.handler..." (screenshot attached). This happens right after "loading terrain" and I can very briefly see something different from the dirt background.

I think this started happening after I entered into one of the thatch houses near spawn; one of them had a flooded basement and I got a disconnect as soon as I logged in. Afterwards I got the error above.

**To Reproduce**
For me: just log in. otherwise: try entering the flooded basement in one of the thatch-roofed houses near spawn.

**Screenshots**
![ConnectionLost](https://user-images.githubusercontent.com/55377899/64940370-14466e00-d864-11e9-86de-83b6ab396b00.PNG)
![NewServer](https://user-images.githubusercontent.com/55377899/64940374-17415e80-d864-11e9-8b3a-7ef11a1060c9.PNG)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: (modded) forge-14.23.5.2847
 - Mod Pack : WoD 19.0.225

**Comment by hellwolf95** [comment] 2019-09-16 12:44
Well give us a bit to figure out what is crashing the server. You arnt lagging out or anything you just cant connect because the server goes down.

**Comment by kreezxil** [comment] 2019-09-16 17:25
Caused by Arcane Essentials, fixed in build 226

**Closed by kreezxil** 2019-09-16 17:25 UTC
