### ISSUE TITLE
[please fix] Tinkers dmg 100+

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#306] opened 2019-08-11 23:25 UTC
**Describe the bug**
With a tinkers construct weapon you are able to put way more quarts than the normal max (which is sharpestest increases dmg by 3ish) and you can put quarts to boost the dmg up to 100 (possibly higher)

**To Reproduce**
1. Create any weapon
2. Get quarts
3. Put as much as you want on weapon
4. 100+ dmg

**Screenshots**

![2019-08-08_20 24 15](https://user-images.githubusercontent.com/45436964/62840759-e36b8b80-bc5c-11e9-841e-f7a3382a7e6b.png)

**Versions:**
 - Minecraft:
 - Forge:
 - Mod Pack: WOD
 - Mod Name: Tinkers Construct

 - Mod Version:12.0.156

**Comment by kreezxil** [comment] 2019-08-11 23:28
I need you to research this in the Tinkers' Construct issue tracker and if not posted post there if you find a related issue that is not current create a new issue and paste this all there plus link it back to here. You're one of my admin so I expect this level of detail and research. If you find a current issue, attach this issue to that one.

**Comment by kreezxil** [comment] 2019-08-22 20:34
This could be an issue with tweakers construct. I'll close this for now as I have readded that and heavily nerfed tinkers in the process.

If this continues to be an issue please make a new issue and add explicit steps and indicate exactly what is being used and where. Turn on tooltip hints with F3+H this will show the the modid:itemname when you mouse over stuff plus also dmg/meta values. We'll need all that.

We need it all because for one slimeknight says he's unable to reproduce it. And by having it all we might find it is caused by another mod entirely and furthermore it might be a feature of the other mod that needs to be disabled or reported.

**Closed by kreezxil** 2019-08-22 20:34 UTC
