### ISSUE TITLE
[please fix] Aluminium/Bauxite Ore

### ISSUE THREAD

**Issue by MisterErwin** [kreezxil/World-of-Dragons#113] opened 2019-03-30 20:21 UTC
**Describe the bug**
All the Aluminium/Aluminum/Bauxite Ores drop the Bauxite Ore from Tech Reborn.

The problem is that ore can't be smelted to aluminium (ingots) and requires an Industrial Electrolyzer to further process it.

**Versions:**
 - Mod Pack 14.38.170

**Additional context**
My suggestion would be to handle Tech Reborns and Immersive Engineerings Bauxite ore different or set the default drop to Immersive Engineerings one

**Comment by kreezxil** [comment] 2019-03-31 10:28
This is caused by the instant unify mod which turns the multiple variants
of the ores into one ore. I consider it great that you can get the
aluminium at least thru a process. Seems the mod is causing issues with
ingot formation as reported by another player with thaumcraft. I'll see if
I can tell it to stop unifying ingots, because ingots was basically not the
problem I was trying to solve.

**Comment by MisterErwin** [comment] 2019-03-31 12:06
The process for alumin(i)um ingots is actually quite... long.
Not sure if that is intended, but currently immersive engineering is practically gated behind Tech Reborns Industrial Electrolyzer (which is a somewhat complex machine).

But :+1:

**Comment by kreezxil** [comment] 2019-04-01 02:22
should be fixed in build 172, will leave this open until we know for sure. You can test this by using my servers right now where the server config is live.

**Comment by kreezxil** [comment] 2019-04-08 12:40
We're gong on 174, I've heard nothing else, marking this closed.

**Closed by kreezxil** 2019-04-08 12:40 UTC
