### ISSUE TITLE
Missing Immersive Engineering plate

### ISSUE THREAD

**Issue by Felronis** [kreezxil/World-of-Dragons#106] opened 2019-03-27 18:18 UTC
Did a glance through to see if anyone else mentioned this and saw nothing so wanted to mention an issue with the questing. For the Power Conversion section the quest "The Plates" requires the copper plate from Immersive Engineering but the Jei shows you can only make Thermal foundation version and there is no IE recipe at all. Sorry if you are aware of this already I'm just a completionist triggered by a small thing lol.

**Comment by kreezxil** [comment] 2019-03-27 21:19
This may be an issue caused by recent pack changes. We'll investigate it
further, thanks for being triggered enough to file a report. :)

**Comment by Drakyl** [comment] 2019-03-29 00:18
edited the quest to use any of the copper plates

**Comment by kreezxil** [comment] 2019-03-29 11:37
fixed in next release of the pack

**Closed by kreezxil** 2019-03-29 11:37 UTC
