### ISSUE TITLE
Numbers indicating Light level on the ground.

### ISSUE THREAD

**Issue by HelloThere91** [kreezxil/World-of-Dragons#318] opened 2019-08-30 18:59 UTC
I pressed a button and the game started displaying numbers on the blocks and I dont know how to get rid of them.

**Comment by IppSwitch** [comment] 2019-08-30 21:21
Press F7 on your keyboard to toggle the numbers.
The numbers represent the current light level on that block. Anything above 6 will not spawn enemies unless configured to do so.

**Comment by kreezxil** [comment] 2019-08-30 23:40
Actually this mod shows 3 colors of number, Green, Yellow, and Red. The
Green numbers are considered to be fully lit and will not spawn mobs unless
a special spawn altering mod is installed such as BloodMoon. The yellow
numbers will spawn mobs if the sun sets or if there is no moon or if
something moves over them to block out even more light. The red numbers
will spawn mobs if you are 35 blocks away from them.

While the numbers are on the ground, if you place a torch, an asterisks
will appear showing you the optimal placement for another torch. The
asterisk can be moved up and down with [ and ] keys to adjust for a
different type of light source that maybe stronger or weaker than a torch.

Pressing F7 will toggle the numbers on and off.

**Comment by kreezxil** [comment] 2019-09-01 17:11
For the love god and all that is holy once you realize you've been given the answer please close your issue report. I'll close it for you. It's proper etiquette btw when you learn it is not a bug but ignorance that is the problem that you would close your own report.

**Closed by kreezxil** 2019-09-01 17:11 UTC
