### ISSUE TITLE
[please add] Binnie's Mods

### ISSUE THREAD

**Issue by amball2000** [kreezxil/World-of-Dragons#141] opened 2019-04-12 05:53 UTC
# Mod Nominated for Adding*
Mod Name: Binnie's Mods
Mod Link: https://minecraft.curseforge.com/projects/binnies-mods

# Reason for Nomination

Reason: I'd love to mess with genetics, grow more types of trees, and make more types of alcohol than what is just in Rustic, as I love diversity. Though if it's too buggy or causes problems I'll submit to you're greater modding experience, as mine is nil.

**Comment by kreezxil** [comment] 2019-04-13 01:21
let's wait and see if I can re-stabilize the pack, if I succeed I'll add it for build 177

**Comment by kreezxil** [comment] 2019-04-15 16:21
this relies on build 367 of Forestry. I don't know if that build is safe yet in regards to the silk touch leaf block harvesting bug, once I test that and verify it to be the case, I'll add this to the pack. If not, i won't and we have to wait on forestry to release a fix.

**Comment by kreezxil** [comment] 2019-04-21 18:17
I'm updating forestry because the bug associated with forestry stopped being reproduceable. so binnies will be in build 179.

**Closed by kreezxil** 2019-04-21 18:17 UTC
Labels: mod suggestion
